# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qp13qk8m-2flT-SmB85WEpZAfVEn6OU5
"""

# feature_engineering.py
import numpy as np
import pandas as pd

def portfolio_return_from_returns(rets_assets: pd.DataFrame, weights: np.ndarray) -> pd.Series:
    """
    rets_assets: DataFrame, rows=dates, cols=tickers, values=daily returns
    weights: array-like, length = number of tickers
    returns: Series portfolio daily return
    """
    w = np.array(weights, dtype=float)
    w = w / w.sum()
    port_ret = rets_assets.values @ w
    return pd.Series(port_ret, index=rets_assets.index, name="portfolio_return")

def build_features_from_returns(
    rets_assets: pd.DataFrame,
    rets_spy: pd.Series,
    weights: np.ndarray,
    window: int = 20
) -> pd.DataFrame:
    """
    Builds a ONE-ROW feature vector with a fixed schema:

    Features (must match training AND real-time):
    - current_vol: rolling std of portfolio return over window
    - portfolio_mean_return: rolling mean of portfolio return over window
    - market_return: rolling mean of SPY return over window
    """
    port_ret = portfolio_return_from_returns(rets_assets, weights)

    X = pd.DataFrame({
        "current_vol": port_ret.rolling(window).std(),
        "portfolio_mean_return": port_ret.rolling(window).mean(),
        "market_return": rets_spy.rolling(window).mean(),
    }).dropna()

    # return the latest available feature row
    return X.tail(1)

def build_stock_features_for_kmeans(rets_assets: pd.DataFrame) -> pd.DataFrame:
    """
    Builds per-stock features for KMeans clustering:
    - avg_return: mean return per stock
    - volatility: std return per stock
    - avg_corr: mean correlation of each stock with others (includes self=1; acceptable for simple project)
    """
    avg_return = rets_assets.mean()
    volatility = rets_assets.std()
    corr = rets_assets.corr()
    avg_corr = corr.mean()

    return pd.DataFrame({
        "avg_return": avg_return,
        "volatility": volatility,
        "avg_corr": avg_corr
    })